name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Pull Docker image from Docker Hub
      run: docker pull midhunmohank/stockmarketprediction
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Push Docker image to Azure Container Registry
      run: |
        az acr login --name myregistry
        docker tag <your-docker-hub-username>/<your-docker-image-name>:<tag> myregistry.azurecr.io/myapp
        docker push myregistry.azurecr.io/myapp
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: myapp
        images: myregistry.azurecr.io/myapp
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}
